# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189YNjfo7KtYFT6N5opbtrsCa1zTN_SYT
"""

print("이번학기에 무언가 새로운 것을 배워 봅시다")

